version: 0.2
#env: 
  #parameter-store:
    #CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain hkhinfocenter --domain-owner 688567289752 --region us-east-1 --query authorizationToken --output text`
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq 
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
      - tar xzvf apache-maven-3.9.11-bin.tar.gz
      - ln -s apache-maven-3.9.11 maven
  build:
    commands:
      - mvn clean install -DskipTests
artifacts:
  files:
     - target/**/*.war
  discard-paths: yes
